jtdx/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('logout/',views.logout,name='logout'),
    path('major/',include('major.urls')),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    path('auction/',include('auction.urls')),
    path('captcha',include('captcha.urls')),
    path('ckeditor',include('ckeditor_uploader.urls')),#富文本路径
]
#设置多媒体上传路径

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.teacher_home,name="teacher_home"),
    path('teacher_register/',views.register,name="teacher_register"),
    path('teacher_task/',views.teacher_task,name='teacher_task'),
    path('teacher_score/',views.teacher_insert_score,name='teacher_score'),
    path('print_name/<int:taskpk>/<int:sign>',views.print_name,name = 'print_name'),
    path('change_score/<int:taskpk>',views.change_score,name='change_score'),
    path('attendance/<int:taskpk>',views.teacher_attendance,name = 'attendance'),
    path('select_teacher/',views.select_teacher,name="select_teacher"),
    path('print_score/<int:taskpk>',views.print_score,name = 'print_score'),
    path('groupteacher/',views.group_teacher,name='groupteacher'),
    path('input_score/<int:coursepk>/<int:semesterpk>/<int:make>',views.input_score,name="input_score"),
    path('print_name/<int:coursepk>/<int:semesterpk>/<int:make>',views.print_name_makeup,name = 'print_name_makeup'),
    path('myclasses/',views.myclasses,name='myclasses'),
    path('teacher_query_score/<int:classespk>',views.teacher_query_score,name='teacher_query_score'),
    path('teacher_query_score/student/<int:studentpk>',views.student_score,name='student_query_score'),
    path('filemaster/',views.filemaster,name="filemaster"),
    path('my_evalution/',views.my_evalution,name="my_evalution"),
   #path('refresh-captcha/',views.refresh_captcha,name="refresh-captcha"),
    path('printclassstudentscore/<int:classpk>',views.print_class_student_scores,name="printclassstudentscore"),
]

attendance/models.py
from django.db import models
from teachingtask.models import TeachingTask
from student.models import Student
# Create your models here.

class AttendanceReason(models.Model):
    name = models.CharField(max_length=20,unique=True)
    def __str__(self):
        return self.name





class Attendance(models.Model):
    task =  models.ForeignKey(TeachingTask,on_delete = models.DO_NOTHING)
    student = models.ForeignKey(Student,on_delete = models.DO_NOTHING)
    #考勤创建时间
    create_time = models.DateTimeField(auto_now_add=True)
    #考勤的时间
    attendance_time = models.DateField()
    #被考勤的原因
    attendance_reason = models.ForeignKey(AttendanceReason,on_delete=models.DO_NOTHING)
    #考勤更改为
    attendance_change =  models.ForeignKey(AttendanceReason,on_delete=models.DO_NOTHING, \
                        blank=True,null=True,related_name="attendance_change")
    #考勤节次
    attendance_detail = models.CharField(max_length=20,null=True)

    class Meta:
         unique_together = ['task','student','attendance_time','attendance_detail']

teacher/forms.py
from django import forms
from .models import Teacher
from teachingtask.models import TeachingTask 
from student.models import Student
from attendance.models import Attendance
from django.contrib.auth.hashers import make_password,check_password
from django.contrib import auth
from django.contrib.auth.models import User
from captcha.fields import CaptchaField

from django.contrib.admin import widgets
from datetimepicker.widgets import DateTimePicker

class TeacherLoginForm(forms.Form):
    username = forms.CharField(label='姓名' \
        ,required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(label='密码' \
        ,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    captcha = CaptchaField(label='验证码')

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username,password=password)
        if user is None:
            raise forms.ValidationError('用户名密码不对')
        else:
            self.cleaned_data['user'] = user
        try:
            captcha_x = self.cleaned_data['captcha']
        except:
            raise forms.ValidationError('验证码错误')
        return self.cleaned_data

class RegTeacherForm(forms.Form):
    username = forms.CharField(label = "用户名" \
        ,max_length=30,min_length=3 \
        ,required=True,widget=forms.TextInput(attrs= \
            {'class':'form-control','placeholder':'yourname'}))

    email = forms.EmailField(label = "邮箱",widget=forms.EmailInput(attrs= \
        {'class':'form-control','placeholder':'jane.doe@example.com'}))

    password =forms.CharField(label = "密码",min_length=6 \
        ,widget=forms.PasswordInput( attrs = {'class':'form-control' \
            ,'placeholder':'密码长度最小为6'}))
    password_again=forms.CharField(label = "确认密码",min_length=6 \
        ,widget=forms.PasswordInput( attrs = {'class':'form-control' \
            ,'placeholder':'在输入一次密码'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名存在')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('email存在')
        return email

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('密码输入的不同')
        return password_again


# class AttendanceForm(forms.ModelForm):
#     class Meta:
#         model = Attendance
#         fields = ['student','attendance_time','attendance_reason']
#         widgets = {
#             'student':forms.Select(attrs={'class':'form-control','multiple':'multiple'}),
#             }
#     def __init__(self,classes = None,**kwargs):
#         super(AttendanceForm,self).__init__(**kwargs)
#         if classes:
#             self.fields['student'].queryset = Student.objects.filter(classes = classes)

class AttendanceForm(forms.Form):
    choices = [
        ("第1节课","第1节课"),
        ("第2节课","第2节课"),
        ("第3节课","第3节课"),
        ("第4节课","第4节课"),
        ("第5节课","第5节课"),
        ("第6节课","第6节课"),
    ]
    student = forms.ModelChoiceField(queryset=None, \
        widget=forms.Select(attrs={'class':'form-control','multiple':'multiple', \
            'placeholder':'选择时间','size':'10'}))
    attendance_time = forms.CharField(label='考勤日期' \
        ,required=True,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'选择时间'}))
    select_detail = forms.ChoiceField(choices = choices)

    #attendance_reason =

    def __init__(self,classes = None ,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['student'].queryset = Student.objects.filter(classes = classes )





# class IScore(forms.ModelForm):
#     class Meta:
#         model = Score
#         fields = ['score','task','student']

teacher/views.py
from django.shortcuts import render,get_object_or_404,HttpResponse,redirect
from .models import Teacher
from .forms import TeacherLoginForm,RegTeacherForm,AttendanceForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib import auth
from django.urls import reverse
from teachingtask.models import TeachingTask,Semester
from score.forms import IScore,CScore
from score.models import Score,Change_Score
from attendance.models import Attendance,AttendanceReason
from django.forms import modelformset_factory,formset_factory
from django.contrib.auth import authenticate
from student.forms import StudentLoginForm
from django.http import JsonResponse
from django.db.models.aggregates import Count
from django.db.models import Max,Avg,Min
from course.models import Course
from jtdx.utils import save_plt_image
from make_up.models import MakeUpTask
from tevaluation.models import Evalution_score,Tevaluation
# Create your views here.
#教师登陆主页
def teacher_home(request):
    #在此是否requestuser检测是否存在用户
    if request.method == 'POST':
        teacherloginform = TeacherLoginForm(request.POST)
        if teacherloginform.is_valid():
            try:
                User.objects.get(username = teacherloginform.cleaned_data['username']). \
                                            teachers.is_teacher
                user = teacherloginform.cleaned_data['user']
                #print(user)
                auth.login(request,user)
                context = {}
                context['group_master'] = User.objects.get(username = teacherloginform. \
                    cleaned_data['username']).teachers.is_group_master
                teacher = Teacher.objects.filter(teacher__username=user)[0]
                context['classesmaster'] = Classes.objects.filter(teacher=teacher).count()
                return render(request,'teacher/teacher_home.html',context)
            except:
                context = {}
                context['message'] = '_____不是______'
                teacherloginform = TeacherLoginForm()
                context['teacherloginform'] = teacherloginform
                return render(request,'teacher/teacher_home.html',context)
        else:
            context = {}
            teacherloginform = TeacherLoginForm()
            context['message'] = '验证码错误'
            #setFormTips(teacherloginform,"验证错误")
            context['teacherloginform'] = teacherloginform
            return render(request,'teacher/teacher_home.html',context)
    else:
        if len(request.user.username)<1:
            context = {}
            context['teacherloginform'] = TeacherLoginForm()
            return render(request,'teacher/teacher_home.html',context)
        else:
            try:
                User.objects.get(username = request.user.username). \
                                                    teachers.is_teacher
                #teacherloginform = TeacherLoginForm()
                name = request.user.username
                #print("___________",name)
                user = User.objects.get(username = name)#如果是个学生如何
                teacher = Teacher.objects.get(teacher = user)
                teachingtasks = TeachingTask.objects.filter(teacher=teacher)
                context = {}
                context['group_master'] = teacher.is_group_master
                context['name'] = name
                context['teachingtasks'] = teachingtasks
                return render(request,'teacher/teacher_task.html',context)
            except:
                context = {}
                context['teacherloginform'] = StudentLoginForm()
                return render(request,'student/student_home.html',context)
#注册
def register(request):
    if request.method == 'POST':
        register_form = RegTeacherForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password']
            email = register_form.cleaned_data['email']
            user = User.objects.create_user(username,email,password)
            newteacher = Teacher()
            newteacher.teacher = user
            newteacher.is_group_master=False
            newteacher.is_teacher = True
            newteacher.save()
            user.save()
            user = auth.authenticate(username=username,password=password)
            auth.login(request,user)
            context = {}
            context['register_form'] = register_form
            context['message'] = '注册成功'
            return render(request,'teacher/teacher_register.html',context)
    else:
        register_form = RegTeacherForm()
    context={}
    context['register_form'] = register_form
    return render(request,'teacher/teacher_register.html',context)

from django.contrib.auth.decorators import login_required,permission_required
#教师教学任务
@login_required(login_url="/teacher/")
def teacher_task(request):
    #添加搜索功能
    tst = request.GET.get("teachersearchtask","")
    tsc = request.GET.get("tsearch","")
    #正常的教学任务
    name = request.user.username
    user = User.objects.get(username = name)
    #如果是个学生如何 使用try 方法解决
    teacher = Teacher.objects.get(teacher = user)
    #得到当前学年学期
    semester = request.GET.get("semester",Semester.objects.get(is_execute = True).pk)
    
    #print(semester)
    
    teachingtasks = TeachingTask.objects.filter(teacher=teacher,semester_id=semester, \
        classes__name__contains=tst,course__name__contains=tsc)
    context = {}
    context['group_master'] = teacher.is_group_master
    #判断该教师是否为班主任
    classesmaster = Classes.objects.filter(teacher = teacher).count()
    context['classesmaster'] = classesmaster
    context['name'] = name
    context['teachingtasks'] = teachingtasks
    #重修的教学任务
    #需要更多的条件,execute_semester=semester
    scores = MakeUpTask.objects.filter(teacher=teacher, \
        execute_semester=semester,is_input = False,course__name__contains=tsc) \
        .values_list('course','semester','make_up')
    #print(scores)
    final_coures ={}
    #任务标记是补考，重修还是其它
    makeupsign = []
    for s in scores:
        if s not in final_coures.keys():
            final_coures[s] = [1,]
        else:
            final_coures[s][0] += 1
        if s[2] not in makeupsign:
            makeupsign.append(s[2])
   # print(makeupsign)
    
    for s in final_coures.keys():
        #print(s[0])
        #print(s[1],"___")
        course = Course.objects.get(pk=s[0])
        semester = Semester.objects.get(pk=s[1])
        final_coures[s].append(course)
        final_coures[s].append(semester)
    #print(final_coures)
    if 2 in makeupsign:
        bukao = True
    else:
        bukao = False
    if 3 in makeupsign:
        chongxiu = True
    else:
        chongxiu = False
    if 4 in makeupsign:
        biyeqian = True
    else:
        biyeqian = False
    context['bukao'] = bukao
    context['chongxiu'] = chongxiu
    context['biyeqian'] = biyeqian
    context['scores'] = final_coures
    context['semesters'] = Semester.objects.all().order_by('-is_execute','-semester_year','semester_period')[:10]
    context['tst'] = tst
    context['tsc'] = tsc
    #print(final_coures)
    return render(request,'teacher/teacher_task.html',context)
    #return redirect(reverse('teacher_task'))

from score.forms import IScore
from student.models import Student
from django.forms import formset_factory

#成绩录入
@login_required(login_url="/teacher/")
def teacher_insert_score(request):
    #教学任务id
    taskpk = request.GET.get('taskpk')
    #判断页面
    is_input_score = request.POST.get('is_input_score',None)
    #成绩录入表单集合
    newformset = formset_factory(IScore,extra=0)
    #生成新的表单
    #如果成绩已经录入了怎么办生成的表单，没有已经录入数据的成绩
    if is_input_score is None or request.method=="GET":
        #教学任务
        task = TeachingTask.objects.get(id=int(taskpk))
        #班级
        classes = task.classes
        #学生名单
        students = Student.objects.filter(classes = classes)
        context = {}
        #构造表单集合的默认数据
        data = []
        for s in students:
            data.append({'student_username':s.student, \
                        'student':str(s.student).split('_')[0], \
                        'task':task,'score':0, \
                        'student_num':s.student_num
                        })
        context['task'] = task
        context['taskpk'] = taskpk
        context['classes'] = classes
        context['iscore']  = newformset(initial = data)
        return render(request,'teacher/teacher_score.html',context)

    #检验表单，并将数据进行存放
    else:
        context = {}
        f = newformset(request.POST,request.FILES)
        context['classes']=request.POST.get('classes')
        context['task'] = request.POST.get('task')
        context['taskpk'] = request.POST.get('taskpk')
        if f.is_valid():
            data = []
            for i in f:
                score = Score()
                score.task = TeachingTask.objects.get(id = int(context['taskpk']))
                #student 模型是User 模型的拓展
                suser = User.objects.get(username=i.cleaned_data['student_username'])
                score.student = Student.objects.get(student=suser)
                score.score = i.cleaned_data['score']
                if Score.objects.filter(task=score.task,student=score.student).exists():
                    #不能更改表单内的内容
                    i.cleaned_data['score'] = Score.objects.filter(task=score.task,student=score.student)[0].score
                    data.append({
                        'student_username':suser.username, \
                        'student':str(suser.username).split('_')[0], \
                        'task':context['task'], \
                        'score':Score.objects.filter(task=score.task,student=score.student)[0].score, \
                        'student_num':score.student.student_num, \
                        })
                # #存入成绩
                else:
                    data.append({

templates/teacher/attendance.html
{% extends 'teacherbase.html' %}
{% load staticfiles %}

{% block header_extends %} 

{% endblock %}

{% block content %}
<!-- {{ students_pk }}
{{ attendance_time }} -->

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
               <span> <h3>{{ task }} </h3></span> 
    <form action="" method="post">
            {% csrf_token %}
            {% for field in formset %}
            {{ field }}
            <p class="text-danger">{{ field.errors.as_text }}</p>
            {% endfor %}
            <span class="pull-left text-danger">{{ formset.non_field_errors }}</span>
            <select name="attendance_reason" id="">
                <option value="迟到">迟到</option>
            </select>
            <input type="hidden" name="taskpk" value="{{ task.pk }}">
            <button type="submit"> 提交 </button>
    </form>
    </div>
    </div>

    <div class="row">
        
            <div class="col-md-8 col-md-offset-2">
                <table class="table">
                {% for a in attendance_set %}
                <tr>
                    <td>{{ a.student }}</td>
                    <td>{{ a.attendance_time }}</td>
                    <td>{{ a.attendance_reason }}</td>
                    <td>{{ a.attendance_detail }}</td>
                {% empty %}
                </tr>
                {% endfor %}
            </table>
            </div>
        
    </div>
        <script type="text/javascript">
            $('#id_attendance_time').datetimepicker({
                format:'yyyy-mm-dd',
                autoclose:true,
                language:'zh-CN',
                minView:'2',
                todayBtn:'linked',
            });
        </script>
{% endblock %}

templates/teacher/changescore.html
{% extends 'teacherbase.html' %}
{% load staticfiles %}


{% block content %}
<!-- {{ task }}
{{ students }}
{{ scores }} -->
<div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h3 class="text-danger text-center">
                每个学生的成绩只能更改一次
                <br/>
                提交后请联系教务
            </h3>
            <h4 class="bg-danger text-center" >教学任务：{{ task }}</h4>
            <!-- {{ taskpk }} -->
            <div class="table-responsive">
                    <table class="table table-hover">
                        <tr>
                            <th></th>
                            <th></th>
                            <th>学号</th>
                            <th>姓名</th>
                            <th>分数</th>
                            <th>改为</th>
                            <th>原因</th>
                        </tr>
            <form action="{% url 'change_score' task.pk %}" method="POST">
                {% csrf_token %}
                {{ formset.management_form }}
                {% for register_form in formset %}
                <tr>
                    {% for field in register_form %}
                        <!-- <label for="{{ field.id_for_label }}">{{ field.label }}</label> -->
                        <td>
                        {{ field }}
                        <p class="text-danger">{{ field.errors.as_text }}</p>
                        </td>
                    {% endfor %}
                        <span class="pull-left text-danger">{{ register_form.non_field_errors }}</span>
                </tr>
                {% endfor %}
                </table>
                </div>
                <input type="submit" value="gooo" class="pull-right">
            </form>
        </div>
    </div>


{% endblock %}

templates/teacher/filemaster.html
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block header_extends %} 
    <link rel="stylesheet" href = "{% static 'bootstrap-3.3.7/css/bootstrap.min.css'%}">
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        {% render_table files%}
    </div>
</div>
{% endblock %}

templates/teacher/my_evalution.html
{% extends 'teacherbase.html' %}
{% load staticfiles %}


{% block content %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
       <img src="{{ image_path }}" alt="{{ teacher }}" class="img-rounded">
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <p align="center">我的最终分{{totalscore}}(总分计算方法：项目平均分*项目权重)</p>
        <table class="table">
                <th>
                    <td>测评项目名称</td>
                    <td>最高分</td>
                    <td>最低分</td>
                    <td>平均分</td>
                    <td>权重</td>
                </th>
        {% for a,b in evalution_score_list.items %}
            <tr>
            <td></td>
            <td>{{ a.name }}</td>
            
            {% for d in b.values %}
               <td> {{ d }}</td>
            {% empty %}
            {% endfor %}
            <td>{{ a.weights }}</td>
        {% empty %}
            </tr>
        {% endfor %}
        </table>
    </div>

</div>
{% endblock %}

templates/teacher/myclasses.html
{% extends 'teacherbase.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        打印平时成绩单
    </title>
    <link rel="stylesheet" href = "{% static 'printbase.css'%}">
    <link rel="stylesheet" href = "{% static 'bootstrap-3.3.7/css/bootstrap.min.css'%}">
    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
</head>
<body>
{% block content %}
<div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>我带的班级</h2>
            <table class="table table-striped">
            <tr>
                <th>序号</th>
                <th>年级</th>
                <th>班级</th>
                <th>专业</th>
                <th>任务</th>
            </tr>
            {% for class in classes%}
                <tr>
                    <td><h5>{{forloop.counter}} </h5></td>
                    <td><h5>{{class.major.grade}}</h5></td>
                    <td><h5>{{class}}</h5></td>
                    <td><h5>{{class.major.name}}</h5></td>
                    <td>
                        <a href="{% url 'print_name' class.pk 1 %}" class="btn btn-info"><h6>打印</br>名单</h6></a>
                        <a href="{% url 'teacher_query_score' class.pk%}" class="btn btn-info"><h6>学生成</br>绩查询</h6></a>
                        <a href="{% url 'printclassstudentscore' class.pk%}" class="btn btn-info"><h6>学生通知</br>成绩打印</h6></a>
                        <a href="" class="btn btn-info"><h6>学生</br>异常填报</h6></a>
                    </td>
                </tr>
            {% empty %}
            <h1>没有信息</h1>
            {% endfor %}
        </table>
        </div>
    </div>
{% endblock %}
</body>

templates/teacher/name.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        打印平时成绩单
    </title>
    <link rel="stylesheet" href = "{% static 'printbase.css'%}">
    <link rel="stylesheet" href = "{% static 'bootstrap-3.3.7/css/bootstrap.min.css'%}">
    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="row">
    <div class="col-md-10 col-md-offset-1">
    <div class="table-responsive">
    <h4>{{ task.classes }}平时成绩单</h4>
    <h5>{{ task }}</h5>
    <table class="table table-bordered table-srtiped">
        <tr>
            <th class="my_th">序号</th>
            <th>学号</th>
            <th class = "my_th">姓名</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        {% if user.is_authenticated %}
            {% for s in students %}
                <tr>
                    <td class="my_td">{{ forloop.counter }}</td>
                    <td class="my_td">{{ s.1 }}</td>
                    <td class="my_td">{{ s.0 }}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
            {% for s in next_index %}
                <tr>
                    <td class="my_td">{{s}}</td>
                    <td class="my_td"></td>
                    <td class="my_td"></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
        
            {% endif %}

    </table>
    </div>
    </div>
    </div>
</body>

templates/teacher/print_score.html
{% extends 'teacherbase.html' %}
{% load staticfiles %}
<!-- {% load render_table from django_tables2 %} -->

{% block content %}

{{ scores_num }}
{{ task }}
    <div class="table">
            <div class="col-md-10 col-md-offset-1">
                <table class="mytable" style ="width:95%;margin:0 auto;">
                    <thead>
                    <tr><th colspan="6" width = "100%"><h3>{{ task.semester }}</h3></th></tr>
                    
                    <tr >
                        <td class = "mytd" rowspan="2" width="8%" height="17" algin="center">学号</td>
                        <td class = "mytd" rowspan="2" width="7%" height="17" algin="center">姓名</td>
                        <td class = "mytd" colspan="3" width="6%" height="17" algin="center">成绩</td>
                        <td class = "mytd" rowspan="2" width="6%" height="17" algin="center">备注</td>
                        <td class = "mytd" rowspan="2" width="8%" height="17" algin="center">学号</td>
                        <td class = "mytd" rowspan="2" width="7%" height="17" algin="center">姓名</td>
                        <td class = "mytd" colspan="3" width="6%" height="17" algin="center">成绩</td>
                        <td class = "mytd" rowspan="2" width="6%" height="17" algin="center">备注</td>
                    </tr>
                    <tr>
                        <td width="6%" height="17" align="center">期末</td>
                        <td width="6%" height="17" align="center">补考</td>
                        <td width="6%" height="17" align="center">重修</td>
                        <td width="6%" height="17" align="center">期末</td>
                        <td width="6%" height="17" align="center">补考</td>
                        <td width="6%" height="17" align="center">重修</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for s in scores %}
                        <tr class="mytd">
                            <!-- <td> {{forloop.counter}}</td> -->
                        {% for i in s %}
                            {% if forloop.counter == 1%}
                            <td class="mytd">{{i.student.student_num}}</td>
                            <td class="mytd">{{i.student.nick_name}}</td>
                            <td class="mytd">{{i.score}}</td>
                            <td class="mytd"></td>
                            <td class="mytd"></td>
                            <td class="mytd"></td>
                            {% else %}
                            <td class="mytd">{{i.student.student_num}}</td>
                            <td class="mytd">{{i.student.nick_name}}</td>
                            <td class="mytd">{{i.score}}</td>
                            <td class="mytd"></td>
                            <td class="mytd"></td>
                            <td class="mytd"></td>
                            {% endif %}
                        {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class= "mytd" rowspan="4" width="8%" height="17">人数统计</td>
                            <td class = "mytd" height="17">
                                <font style="font-size: 12px"> 班级总人数</font>
                               
                            </td>
                            <td class = "mytd" height="17">未参加人数</td>
                            <td class = "mytd" height="17">作弊人数</td>
                            <td class = "mytd" height="17">实考人数</td>
                            <td class = "mytd" height="17">实考人数</td>
                            <td class = "mytd" rowspan="4" colspan="6" width="8%"></td>
                        </tr>
                        <tr>
                                <td class = "mytd" height="17">班级总人数</td>
                                <td class = "mytd" height="17">未参加人数</td>
                                <td class = "mytd" height="17">作弊人数</td>
                                <td class = "mytd" height="17">实考人数</td>
                                <td class = "mytd" height="17">实考人数</td>
                        </tr>
                        <tr>
                                <td class = "mytd" height="17">班级总人数</td>
                                <td class = "mytd" height="17">未参加人数</td>
                                <td class = "mytd" height="17">作弊人数</td>
                                <td class = "mytd" height="17">实考人数</td>
                                <td class = "mytd" height="17">实考人数</td>
                        </tr>
                        <tr>
                                <td class = "mytd" height="17">班级总人数</td>
                                <td class = "mytd" height="17">未参加人数</td>
                                <td class = "mytd" height="17">作弊人数</td>
                                <td class = "mytd" height="17">实考人数</td>
                                <td class = "mytd" height="17">实考人数</td>
                        </tr>
                    </tfoot>
                        
                </table>
            </div>
    </div>




{% endblock %}